elasticsearch:
  image: elasticsearch

logstash:
  image: logstash
  command: logstash -e 'input { tcp { port => 9290 tags => "tcpin" codec => "json" } } output { elasticsearch { hosts => [elasticsearch] } }'
  # environment:
    # CONFIG: input { tcp { port => 9290 tags => "tcpin" codec => "json" } } output { elasticsearch { host => elasticsearch } }
  ports:
   - "9290:9290" #tcpin port
   - "4560:4560" #log4j port
  links:
    - elasticsearch:elasticsearch

kibana:
  image: kibana
  links:
    - elasticsearch:elasticsearch
  ports:
    - "5601:5601" #kibana port

docker2logstash:
  image: sath89/docker2logstash
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - logstash:logstash
