logstash:
  image: sath89/logstash
  environment:
    CONFIG: input {tcp { port => 9290 tags => "tcpin" codec => "json" } } output { elasticsearch { embedded => true } }
  ports:
   - "9301:9301"
   - "9300:9300"
   - "9290:9290"

docker2logstash:
  image: sath89/docker2logstash
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - logstash:logstash

kibana:
  image: sath89/kibana
  links:
    - logstash:elasticsearch
  ports:
    - "5601:5601"