logstash:
  image: sath89/logstash
  environment:
    CONFIG: input {tcp { port => 9290 tags => "tcpin" codec => "json" } } output { elasticsearch { embedded => true } }
    WEB: web
  ports:
   - "9292:9292"
   - "9290:9290"
   - "9200:9200"

docker2logstash:
  image: sath89/docker2logstash
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - logstash:logstash